In [1]:
import numpy as np
a=np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [2]:
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
b=np.matrix([[3],[4],[5]])
b

matrix([[3],
        [4],
        [5]])

In [4]:
a*b

matrix([[26],
        [62],
        [98]])

In [5]:
a.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [6]:
from numpy import linalg as la

In [9]:
la.matrix_rank(a)

2

# Inverse of Matrix only exist if all of columns are linearly independent, Determinant if non-zero and there is no zero in th diagonal
